### ISSUE TITLE
Any plans to expand to add network support?

### ISSUE THREAD

**Issue by nimaim** [vsergeev/c-periphery#13]
First off, thank you very much for this library @vsergeev. It is very clean, easy to understand, and easy to use (and actually documented). I don't know of any other C library that supports these basic functions. I know this is called c-periphery for a reason, but are there any plans to add network functions to this (i.e. TCP/UDP, socket open, send, recv, etc.)? I think it could be very useful as you usually need a much larger library (i.e. Qt, Boost.Asio, etc.) to do this reliably.

I could look into a pull request in the future as time allows ... but didn't know if you wanted to merge in such changes. Thanks.

**Comment by vsergeev** [comment]
Thanks for the kind words. I think the network equivalent would be a good idea, but probably is a big enough project to warrant its own library and associated wrappers (e.g. Lua and Python, etc.).
