### ISSUE TITLE
Any plans to add serial_readline() in serial.c?

### ISSUE THREAD

**Issue by Livius90** [vsergeev/c-periphery#18]
Do you have any plans to implement serial_readline() with configurable newline character and a timeout? It should be a nice feature in your useful c-periphery libs.

**Comment by vsergeev** [comment]
This would be nice, but unfortunately would require buffering in c-periphery. Since this library was meant more for lightweight language bindings, I'm going to punt this to the application or binding layer for now. Perhaps will revisit one day if there's more interest.
