### ISSUE TITLE
SPI R/W REG

### ISSUE THREAD

**Issue by ChayMa19** [vsergeev/c-periphery#39]
Hello,

I am working on a module that use the SPI communication
I should write/read in/from specific registers of this module
My question Is there any example of this issue using  this python package ?

Thank you.

Best regards,

**Comment by vsergeev** [comment]
Register access isn't standardized over SPI, so it will really depend on the part. I'm not sure of any examples off hand, but you may be able to find some with the GitHub code search: https://github.com/search?p=3&q=%22from+periphery+import+SPI%22&type=Code

**Comment by vsergeev** [comment]
If you have the part number of your device (and it has a public datasheet), I may be able to help you get started.
