### ISSUE TITLE
Jetson Nano - not operate discrete output (GPIO), SPI works

### ISSUE THREAD

**Issue by Ildaron** [vsergeev/c-periphery#46]
Hi,  I created static  library .so from your dynamic a. library for control GPIO via python script. But discrete output not operates in Jetson Nano (SPI works), maybe Jetson nano some specific ?
https://github.com/Ildaron/EEG-with-JetsonNano/tree/master/GUI 

Exactly same code works in Raspbian without any problems.

**Comment by vsergeev** [comment]
This is likely a platform configuration issue with the Jetson Nano, which unfortunately I can't help debug. You could try using the `gpio-utils` package to confirm the GPIOs are working outside of c-periphery.

Closing for now, but feel free to re-open if you believe it's an issue with c-periphery.
