### ISSUE TITLE
BeagleBone Black + Yocto not working

### ISSUE THREAD

**Issue by bernardoaraujor** [vsergeev/c-periphery#7]
GPIO test failed at test_loopback.

Built with yocto for a BeagleBone Black.

**Comment by vsergeev** [comment]
Did you have a physical loopback installed between the two GPIOs?

**Comment by bernardoaraujor** [comment]
yeap

**Comment by vsergeev** [comment]
Could you provide the log of the run?

**Comment by bernardoaraujor** [comment]
Picture of the physical loopback: https://goo.gl/photos/1h5nGFbwL6nCPvdW6

Here's the log of the whole process, including steps used for Yocto's devtool:

bernardo@bernardo-ThinkCentre-Edge72:~/yocto/bbb$ devtool add ~/c-periphery/
NOTE: Creating workspace layer in /home/bernardo/yocto/bbb/workspace
NOTE: Enabling workspace layer in bblayers.conf
NOTE: Using source tree as build directory since that would be the default for this recipe
NOTE: Recipe /home/bernardo/yocto/bbb/workspace/recipes/c-periphery/c-periphery_git.bb has been automatically created; further editing may be required to make it fully functional
bernardo@bernardo-ThinkCentre-Edge72:~/yocto/bbb$ cat conf/local.conf 
#
# This file is your local configuration file and is where all local user settings
# are placed. The comments in this file give some guide to the options a new user
# to the system might want to change but pretty much any configuration option can
# be set in this file. More adventurous users can look at local.conf.extended
# which contains other examples of configuration which can be placed in this file
# but new users likely won't need any of them initially.
#
# Lines starting with the '#' character are commented out and in some cases the
# default values are provided as comments to show people example syntax. Enabling
# the option is a question of removing the # character and making any change to the
# variable as required.

#
# Machine Selection
#
# You need to select a specific machine to target the build with. There are a selection
# of emulated machines available which can boot and run in the QEMU emulator:
#
#MACHINE ?= "qemuarm"
#MACHINE ?= "qemuarm64"
#MACHINE ?= "qemumips"
#MACHINE ?= "qemumips64"
#MACHINE ?= "qemuppc"
#MACHINE ?= "qemux86"
#MACHINE ?= "qemux86-64"
#
# There are also the following hardware board target machines included for 
# demonstration purposes:
#
#MACHINE ?= "beaglebone"
#MACHINE ?= "genericx86"
#MACHINE ?= "genericx86-64"
#MACHINE ?= "mpc8315e-rdb"
#MACHINE ?= "edgerouter"
#
# This sets the default machine to be qemux86 if no other machine is selected:
MACHINE ??= "qemux86"

#
# Where to place downloads
#
# During a first build the system will download many different source code tarballs
# from various upstream projects. This can take a while, particularly if your network
# connection is slow. These are all stored in DL_DIR. When wiping and rebuilding you
# can preserve this directory to speed up this part of subsequent builds. This directory
# is safe to share between multiple builds on the same machine too.
#
# The default is a downloads directory under TOPDIR which is the build directory.
#
#DL_DIR ?= "${TOPDIR}/downloads"

#
# Where to place shared-state files
#
# BitBake has the capability to accelerate builds based on previously built output.
# This is done using "shared state" files which can be thought of as cache objects
# and this option determines where those files are placed.
#
# You can wipe out TMPDIR leaving this directory intact and the build would regenerate
# from these files if no changes were made to the configuration. If changes were made
# to the configuration, only shared state files where the state was still valid would
# be used (done using checksums).
#
# The default is a sstate-cache directory under TOPDIR.
#
#SSTATE_DIR ?= "${TOPDIR}/sstate-cache"

#
# Where to place the build output
#
# This option specifies where the bulk of the building work should be done and
# where BitBake should place its temporary files and output. Keep in mind that
# this includes the extraction and compilation of many applications and the toolchain
# which can use Gigabytes of hard disk space.
#
# The default is a tmp directory under TOPDIR.
#
#TMPDIR = "${TOPDIR}/tmp"

#
# Default policy config
#
# The distribution setting controls which policy settings are used as defaults.
# The default value is fine for general Yocto project use, at least initially.
# Ultimately when creating custom policy, people will likely end up subclassing 
# these defaults.
#
DISTRO ?= "poky"
# As an example of a subclass there is a "bleeding" edge policy configuration
# where many versions are set to the absolute latest code from the upstream 
# source control systems. This is just mentioned here as an example, its not
# useful to most new users.
# DISTRO ?= "poky-bleeding"

#
# Package Management configuration
#
# This variable lists which packaging formats to enable. Multiple package backends
# can be enabled at once and the first item listed in the variable will be used
# to generate the root filesystems.
# Options are:
#  - 'package_deb' for debian style deb files
#  - 'package_ipk' for ipk files are used by opkg (a debian style embedded package manager)
#  - 'package_rpm' for rpm style packages
# E.g.: PACKAGE_CLASSES ?= "package_rpm package_deb package_ipk"
# We default to rpm:
PACKAGE_CLASSES ?= "package_rpm"

#
# SDK target architecture
#
# This variable specifies the architecture to build SDK items for and means
# you can build the SDK packages for architectures other than the machine you are
# running the build on (i.e. building i686 packages on an x86_64 host).
# Supported values are i686 and x86_64
#SDKMACHINE ?= "i686"

#
# Extra image configuration defaults
#
# The EXTRA_IMAGE_FEATURES variable allows extra packages to be added to the generated
# images. Some of these options are added to certain image types automatically. The
# variable can contain the following options:
#  "dbg-pkgs"       - add -dbg packages for all installed packages
#                     (adds symbol information for debugging/profiling)
#  "dev-pkgs"       - add -dev packages for all installed packages
#                     (useful if you want to develop against libs in the image)
#  "ptest-pkgs"     - add -ptest packages for all ptest-enabled packages
#                     (useful if you want to run the package test suites)
#  "tools-sdk"      - add development tools (gcc, make, pkgconfig etc.)
#  "tools-debug"    - add debugging tools (gdb, strace)
#  "eclipse-debug"  - add Eclipse remote debugging support
#  "tools-profile"  - add profiling tools (oprofile, lttng, valgrind)
#  "tools-testapps" - add useful testing tools (ts_print, aplay, arecord etc.)
#  "debug-tweaks"   - make an image suitable for development
#                     e.g. ssh root access has a blank password
# There are other application targets that can be used here too, see
# meta/classes/image.bbclass and meta/classes/core-image.bbclass for more details.
# We default to enabling the debugging tweaks.
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"

#
# Additional image features
#
# The following is a list of additional classes to use when building images which
# enable extra features. Some available options which can be included in this variable
# are:
#   - 'buildstats' collect build statistics
#   - 'image-mklibs' to reduce shared library files size for an image
#   - 'image-prelink' in order to prelink the filesystem image
#   - 'image-swab' to perform host system intrusion detection
# NOTE: if listing mklibs & prelink both, then make sure mklibs is before prelink
# NOTE: mklibs also needs to be explicitly enabled for a given image, see local.conf.extended
# image-prelink disabled for now due to issues with IFUNC symbol relocation
USER_CLASSES ?= "buildstats image-mklibs"

#
# Runtime testing of images
#
# The build system can test booting virtual machine images under qemu (an emulator)
# after any root filesystems are created and run tests against those images. To
# enable this uncomment this line. See classes/testimage(-auto).bbclass for
# further details.
#TEST_IMAGE = "1"
#
# Interactive shell configuration
#
# Under certain circumstances the system may need input from you and to do this it
# can launch an interactive shell. It needs to do this since the build is
# multithreaded and needs to be able to handle the case where more than one parallel
# process may require the user's attention. The default is iterate over the available
# terminal types to find one that works.
#
# Examples of the occasions this may happen are when resolving patches which cannot
# be applied, to use the devshell or the kernel menuconfig
#
# Supported values are auto, gnome, xfce, rxvt, screen, konsole (KDE 3.x only), none
# Note: currently, Konsole support only works for KDE 3.x due to the way
# newer Konsole versions behave
#OE_TERMINAL = "auto"
# By default disable interactive patch resolution (tasks will just fail instead):
PATCHRESOLVE = "noop"

#
# Disk Space Monitoring during the build
#
# Monitor the disk space during the build. If there is less that 1GB of space or less
# than 100K inodes in any key build location (TMPDIR, DL_DIR, SSTATE_DIR), gracefully
# shutdown the build. If there is less that 100MB or 1K inodes, perform a hard abort
# of the build. The reason for this is that running completely out of space can corrupt
# files and damages the build in ways which may not be easily recoverable.
# It's necesary to monitor /tmp, if there is no space left the build will fail
# with very exotic errors.
BB_DISKMON_DIRS = "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    ABORT,${TMPDIR},100M,1K \
    ABORT,${DL_DIR},100M,1K \
    ABORT,${SSTATE_DIR},100M,1K \
    ABORT,/tmp,10M,1K"

#
# Shared-state files from other locations
#
# As mentioned above, shared state files are prebuilt cache data objects which can
# used to accelerate build time. This variable can be used to configure the system
# to search other mirror locations for these objects before it builds the data itself.
#
# This can be a filesystem directory, or a remote url such as http or ftp. These
# would contain the sstate-cache results from previous builds (possibly from other
# machines). This variable works like fetcher MIRRORS/PREMIRRORS and points to the
# cache locations to check for the shared objects.
# NOTE: if the mirror uses the same structure as SSTATE_DIR, you need to add PATH
# at the end as shown in the examples below. This will be substituted with the
# correct path within the directory structure.
#SSTATE_MIRRORS ?= "\
#file://.* http://someserver.tld/share/sstate/PATH;downloadfilename=PATH \n \
#file://.* file:///some/local/dir/sstate/PATH"


#
# Qemu configuration
#
# By default qemu will build with a builtin VNC server where graphical output can be
# seen. The two lines below enable the SDL backend too. By default libsdl-native will
# be built, if you want to use your host's libSDL instead of the minimal libsdl built
# by libsdl-native then uncomment the ASSUME_PROVIDED line below.
PACKAGECONFIG_append_pn-qemu-native = " sdl"
PACKAGECONFIG_append_pn-nativesdk-qemu = " sdl"
#ASSUME_PROVIDED += "libsdl-native"

# CONF_VERSION is increased each time build/conf/ changes incompatibly and is used to
# track the version of this file when it was generated. This can safely be ignored if
# this doesn't mean anything to you.
CONF_VERSION = "1"
PACKAGE_CLASSES = "package_ipk"
MACHINE = "beaglebone"
PREFERRED_PROVIDER_virtual/kernel_beaglebone = "linux-ti-staging-rt"
IMAGE_BOOT_FILES_beaglebone = "u-boot.img MLO"
IMAGE_INSTALL_append_beaglebone = " kernel-modules kernel-devicetree"
IMAGE_INSTALL_append_beaglebone = " connman"
IMAGE_INSTALL_append_beaglebone = " connman-client"
IMAGE_INSTALL_append_beaglebone = " openssh openssh-sftp openssh-sftp-server"
IMAGE_INSTALL_append_beaglebone = " i2c-tools"
IMAGE_INSTALL_append_beaglebone = " git"
PREFERRED_PROVIDER_virtual/kernel = "linux-yocto-rt"
BB_NUMBER_THREADS ?= "6"
PARALLEL_MAKE ?= "-j 8"

EXTRA_IMAGE_FEATURES = " debug-tweaks"
bernardo@bernardo-ThinkCentre-Edge72:~/yocto/bbb$ cat conf/bblayers.conf 
# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/bernardo/yocto/poky-krogoth/meta \
  /home/bernardo/yocto/poky-krogoth/meta-poky \
  /home/bernardo/yocto/poky-krogoth/meta-ti \
  /home/bernardo/yocto/bbb/workspace \
  "
bernardo@bernardo-ThinkCentre-Edge72:~/yocto/bbb$ nano workspace/recipes/c-periphery/c-periphery_git.bb 
bernardo@bernardo-ThinkCentre-Edge72:~/yocto/bbb$ devtool build c-periphery
Parsing recipes: 100% |############################################################################################################################################################################| Time: 00:00:37
Parsing of 1032 .bb files complete (0 cached, 1032 parsed). 1470 targets, 153 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.30.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "universal"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "beaglebone"
DISTRO            = "poky"
DISTRO_VERSION    = "2.1.2"
TUNE_FEATURES     = "arm armv7a vfp thumb neon       callconvention-hard"
TARGET_FPU        = "hard"
meta              
meta-poky         = "krogoth:ae9b341ecfcc60e970f29cfe04306411ad26c0cf"
meta-ti           = "krogoth:f0a7e52d65861a432ff94f2465e67e014cc7eca0"
workspace         = "<unknown>:<unknown>"

NOTE: Preparing RunQueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
c-periphery-1.0+git999-r0 do_compile: NOTE: c-periphery: compiling from external source tree /home/bernardo/c-periphery
NOTE: Tasks Summary: Attempted 333 tasks of which 327 didn't need to be rerun and all succeeded.
bernardo@bernardo-ThinkCentre-Edge72:~/yocto/bbb$ devtool deploy-target c-periphery root@10.0.16.35
Parsing recipes..done.
The authenticity of host '10.0.16.35 (10.0.16.35)' can't be established.
ECDSA key fingerprint is 31:65:43:1a:94:e4:f3:03:cc:b5:cd:9f:f7:88:65:22.
Are you sure you want to continue connecting (yes/no)? yes
The authenticity of host '10.0.16.35 (10.0.16.35)' can't be established.
ECDSA key fingerprint is 31:65:43:1a:94:e4:f3:03:cc:b5:cd:9f:f7:88:65:22.
Are you sure you want to continue connecting (yes/no)? yes
NOTE: Successfully deployed /home/bernardo/yocto/bbb/tmp/work/armv7ahf-neon-poky-linux-gnueabi/c-periphery/1.0+git999-r0/image
bernardo@bernardo-ThinkCentre-Edge72:~/yocto/bbb$ ssh root@10.0.16.35
The authenticity of host '10.0.16.35 (10.0.16.35)' can't be established.
ECDSA key fingerprint is 31:65:43:1a:94:e4:f3:03:cc:b5:cd:9f:f7:88:65:22.
Are you sure you want to continue connecting (yes/no)? yes
Failed to add the host to the list of known hosts (/home/bernardo/.ssh/known_hosts).
Last login: Wed Jan 18 09:57:39 2017 from 10.0.16.34
root@beaglebone:~# test_gpio
Usage: test_gpio <pin #1> <pin #2>

[1/4] Argument test: No requirements.
[2/4] Open/close test: GPIO pin #2 should be real.
[3/4] Loopback test: GPIOs #1 and #2 should be connected with a wire.
[4/4] Interactive test: GPIO #2 should be observed with a multimeter.

Hint: for BeagleBone Black, connect a wire between
GPIO 38 (P8.3, gpio1[6]) and GPIO 39 (P8.4, gpio1[7]),
then run this test with:
    test_gpio 38 39

root@beaglebone:~# test_gpio 38 39

Starting test test_arguments():22
 [ OK ]  tests/test_gpio.c test_arguments():25  gpio_open(&gpio, pin_input, 5) == GPIO_ERROR_ARG
 [ OK ]  Arguments test passed.


Starting test test_open_config_close():34
 [ OK ]  tests/test_gpio.c test_open_config_close():37  gpio_open(&gpio, -1, GPIO_DIR_IN) == GPIO_ERROR_EXPORT
 [ OK ]  tests/test_gpio.c test_open_config_close():38  gpio_errno(&gpio) == EINVAL
 [ OK ]  tests/test_gpio.c test_open_config_close():41  gpio_open(&gpio, pin_output, GPIO_DIR_IN) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():44  gpio_set_direction(&gpio, 5) == GPIO_ERROR_ARG
 [ OK ]  tests/test_gpio.c test_open_config_close():46  gpio_set_edge(&gpio, 5) == GPIO_ERROR_ARG
 [ OK ]  tests/test_gpio.c test_open_config_close():49  gpio_set_direction(&gpio, GPIO_DIR_OUT) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():50  gpio_get_direction(&gpio, &direction) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():51  direction == GPIO_DIR_OUT
 [ OK ]  tests/test_gpio.c test_open_config_close():52  gpio_read(&gpio, &value) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():53  value == false
 [ OK ]  tests/test_gpio.c test_open_config_close():55  gpio_set_direction(&gpio, GPIO_DIR_OUT_LOW) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():56  gpio_get_direction(&gpio, &direction) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():57  direction == GPIO_DIR_OUT
 [ OK ]  tests/test_gpio.c test_open_config_close():58  gpio_read(&gpio, &value) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():59  value == false
 [ OK ]  tests/test_gpio.c test_open_config_close():61  gpio_set_direction(&gpio, GPIO_DIR_OUT_HIGH) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():62  gpio_get_direction(&gpio, &direction) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():63  direction == GPIO_DIR_OUT
 [ OK ]  tests/test_gpio.c test_open_config_close():64  gpio_read(&gpio, &value) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():65  value == true
 [ OK ]  tests/test_gpio.c test_open_config_close():67  gpio_set_direction(&gpio, GPIO_DIR_IN) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():68  gpio_get_direction(&gpio, &direction) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():69  direction == GPIO_DIR_IN
 [ OK ]  tests/test_gpio.c test_open_config_close():70  gpio_read(&gpio, &value) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():73  gpio_supports_interrupts(&gpio, &interrupts_supported) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():74  interrupts_supported == true
 [ OK ]  tests/test_gpio.c test_open_config_close():77  gpio_set_edge(&gpio, GPIO_EDGE_NONE) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():78  gpio_get_edge(&gpio, &edge) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():79  edge == GPIO_EDGE_NONE
 [ OK ]  tests/test_gpio.c test_open_config_close():81  gpio_set_edge(&gpio, GPIO_EDGE_RISING) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():82  gpio_get_edge(&gpio, &edge) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():83  edge == GPIO_EDGE_RISING
 [ OK ]  tests/test_gpio.c test_open_config_close():85  gpio_set_edge(&gpio, GPIO_EDGE_FALLING) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():86  gpio_get_edge(&gpio, &edge) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():87  edge == GPIO_EDGE_FALLING
 [ OK ]  tests/test_gpio.c test_open_config_close():89  gpio_set_edge(&gpio, GPIO_EDGE_BOTH) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():90  gpio_get_edge(&gpio, &edge) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():91  edge == GPIO_EDGE_BOTH
 [ OK ]  tests/test_gpio.c test_open_config_close():93  gpio_set_edge(&gpio, GPIO_EDGE_NONE) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():94  gpio_get_edge(&gpio, &edge) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():95  edge == GPIO_EDGE_NONE
 [ OK ]  tests/test_gpio.c test_open_config_close():98  gpio_close(&gpio) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():101  gpio_open(&gpio, pin_output, GPIO_DIR_OUT) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():103  gpio_close(&gpio) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():105  gpio_open(&gpio, pin_output, GPIO_DIR_PRESERVE) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():107  gpio_get_direction(&gpio, &direction) == 0
 [ OK ]  tests/test_gpio.c test_open_config_close():108  direction == GPIO_DIR_OUT
 [ OK ]  tests/test_gpio.c test_open_config_close():111  gpio_close(&gpio) == 0
 [ OK ]  Open/close test passed.


Starting test test_loopback():118
 [ OK ]  tests/test_gpio.c test_loopback():121  gpio_open(&gpio_in, pin_input, GPIO_DIR_IN) == 0
 [ OK ]  tests/test_gpio.c test_loopback():122  gpio_open(&gpio_out, pin_output, GPIO_DIR_OUT) == 0
 [ OK ]  tests/test_gpio.c test_loopback():125  gpio_write(&gpio_out, false) == 0
 [ OK ]  tests/test_gpio.c test_loopback():126  gpio_read(&gpio_in, &value) == 0
 [ OK ]  tests/test_gpio.c test_loopback():127  value == false
 [ OK ]  tests/test_gpio.c test_loopback():130  gpio_write(&gpio_out, true) == 0
 [ OK ]  tests/test_gpio.c test_loopback():131  gpio_read(&gpio_in, &value) == 0
 [FAIL]  tests/test_gpio.c test_loopback():132  value == true
test_gpio: tests/test_gpio.c:132: test_loopback: Assertion `r' failed.
Aborted

**Comment by bernardoaraujor** [comment]
oops.. forgot to cat workspace/recipes/c-periphery/c-periphery_git.bb

I'll do it in a minute.

**Comment by vsergeev** [comment]
I bet your GPIO numbers are somehow mapped differently. What kernel are you using?

Surest way to check though is with a multimeter on GPIO 38 (P8.3) and manually writing 1 or 0 `/sys/class/gpio/gpio38/value`, after writing `out` to `/sys/class/gpio/gpio38/direction`.

**Comment by bernardoaraujor** [comment]
Indeed. Reproduced the commands, but the voltimeter reads only 3.3v, even after echoing 0.

**Comment by vsergeev** [comment]
I've been running Arch Linux ARM, which is currently on 4.10.4. But the Linux package is the linux-am33x variant, which may have the GPIO mapping expected by the test.

**Comment by vsergeev** [comment]
I'm going to close this issue for now, as it's just a platform configuration issue, rather than a library issue. But feel free to follow up here on the GPIO mapping.
